### ISSUE TITLE
How can I find examples of performing "Point addition experiments"?

### ISSUE THREAD

**Issue by ffgg11** [opendataval/opendataval#11]
Thanks to the author for releasing a nice open source implementation.  It will be of great help to the community. But when I allow your code, I have a question as follows: How can I find examples of performing "Point addition experiments"?

**Comment by ykwon0407** [comment]
Thank you for your interest and kind words! The point addition experiment can also be conducted using `remove_high_low`. If you remove data points from the original training dataset, starting from the most helpful (e.g., data points with the largest value) to the least helpful (data points with the lowest value), it essentially performs the same experiment as adding data points from the null set, starting from the lowest to the largest.
