### ISSUE TITLE
Example one-hot-encoding custom-dataset_classification.ipynb

### ISSUE THREAD

**Issue by cruyffturn** [opendataval/opendataval#13]
### 🐛 Describe the bug

Hello,

Thank you for all your work for this package. In the custom-dataset_classification.ipynb, the labels are in {0,1} but the Register was passed in one_hot=True. Does that consists an error?

Thanks!

### Operating System

None

**Comment by ykwon0407** [comment]
Hi @cruyffturn, `one_hot=True` in `custom-dataset_classification.ipynb` is not an error. It will change your labels from integer representations to one-hot representations via `self.label_transform`. Please see `Register` defined in [this line](https://github.com/opendataval/opendataval/blob/6888e8c34564849d15af912ca4fe44d07c42282f/opendataval/dataloader/register.py#L108). This `self.label_transform` is called at [this line](https://github.com/opendataval/opendataval/blob/6888e8c34564849d15af912ca4fe44d07c42282f/opendataval/dataloader/register.py#L265)
