### ISSUE TITLE
how to put data on GPU

### ISSUE THREAD

**Issue by xxbean** [opendataval/opendataval#22]
device = torch.device('cuda') 

    fetcher.x_train = fetcher.x_train.to(device)   

    fetcher.y_train = fetcher.y_train.to(device)   

    fetcher.x_valid = fetcher.x_valid.to(device)   

    fetcher.y_valid = fetcher.y_valid.to(device)   

    fetcher.x_test = fetcher.x_test.to(device)  

    fetcher.y_test = fetcher.y_test.to(device)

I also want to use the data in gpu, so I keep getting the following error after using that method

`%%time    exper_med = exper_med.compute_data_values(data_evaluators=data_evaluators)`
```
Start: marginal contribution computation
/usr/local/lib/python3.10/dist-packages/opendataval/dataloader/fetcher.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_trn = torch.tensor(self.y_train, dtype=torch.float).view(-1, *self.label_dim)
/usr/local/lib/python3.10/dist-packages/opendataval/dataloader/fetcher.py:277: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_val = torch.tensor(self.y_valid, dtype=torch.float).view(-1, *self.label_dim)
/usr/local/lib/python3.10/dist-packages/opendataval/dataloader/fetcher.py:278: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test = torch.tensor(self.y_test, dtype=torch.float).view(-1, *self.label_dim)
  0%|          | 0/100 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3473: UserWarning: 
                    An error occured during training, however training all evaluators
                    takes a long time, so we will be ignoring the evaluator:
                    DataShapley(gr_threshold=1.05, cache_name=cached) and proceeding.

                    The error is as follows: cannot pin 'torch.cuda.FloatTensor' only dense CPU tensors can be pinned
                    
  if (await self.run_code(code, result,  async_=asy)):
  0%|          | 0/100 [00:00<?, ?it/s]CPU times: user 31.1 ms, sys: 0 ns, total: 31.1 ms
Wall time: 85.4 ms 
```

How can I solve it? I also want to transfer data to gpu and use it

**Comment by xxbean** [comment]
I also use model 'Lenet'

**Comment by ykwon0407** [comment]
Hi @xxbean, you can utilize GPU without using `to(device)`. Simply, specify the `device` argument in `ExperimentMediator.model_factory_setup` to access GPUs/MPSs. The following is an example from [the BBC notebook](https://github.com/opendataval/opendataval/blob/main/examples/bbc_classification.ipynb). 

```
dataset_name = "bbc" 
train_count, valid_count, test_count = 1000, 100, 500
noise_rate = 0.1
noise_kwargs = {'noise_rate': noise_rate}
model_name = "BertClassifier"
metric_name = "accuracy"
train_kwargs = {"epochs": 2, "batch_size": 50}
device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'

exper_med = ExperimentMediator.model_factory_setup(
    dataset_name=dataset_name,
    cache_dir="../data_files/",  
    force_download=False,
    train_count=train_count,
    valid_count=valid_count,
    test_count=test_count,
    add_noise=mix_labels,
    noise_kwargs=noise_kwargs,
    train_kwargs=train_kwargs,
    device=device,
    model_name=model_name,
    metric_name=metric_name
)
```

**Comment by xxbean** [comment]
thanks .but then I cannot use the below option? 
cause I want to split my data ,not use count option
`
fetcher = (
    DataFetcher(dataset_name, '/data1/opendatavalshapley', False).from_data_splits(
    x_train, y_train ,x_valid, y_valid , x_test, y_test ,one_hot=False).noisify(mix_labels, noise_rate=noise_rate))`

**Comment by ykwon0407** [comment]
Thanks for the clarification! Loading data onto GPUs isn't necessary when defining `fetcher`. Data will be automatically loaded only when it is used in training. 

For instance, as in this [line](https://github.com/opendataval/opendataval/blob/747f1b8d2414e0fef193a5e4de20cd9cb4a5e8b8/opendataval/experiment/api.py#L211C22-L211C34), GPU devices will be needed to set when `Model` is created, and data will be loaded when `model.fit()` is called.
