### ISSUE TITLE
Default value for number of epochs in the paper

### ISSUE THREAD

**Issue by twibiral** [opendataval/opendataval#26]
Hi,
I just saw that the default number of training epochs is just 1. For how many epochs did you train the models for the paper? Was 1 epoch sufficient, or did you train the model for more?

**Comment by ykwon0407** [comment]
Hi @twibiral, thank you for the question! Yes, you are correct that the default number of training epochs is 1, as in this [line](https://github.com/opendataval/opendataval/blob/747f1b8d2414e0fef193a5e4de20cd9cb4a5e8b8/opendataval/model/api.py#L108). But, this argument is not utilized when [the sklearn wrapper](https://github.com/opendataval/opendataval/blob/747f1b8d2414e0fef193a5e4de20cd9cb4a5e8b8/opendataval/model/api.py#L259) is called. In our experiments, we used this sklearn wrapper.

**Comment by twibiral** [comment]
Hi, @ykwon0407, thank you a lot for the clarification!
