### ISSUE TITLE
Retrieve original datapoints/indexes

### ISSUE THREAD

**Issue by heblol** [opendataval/opendataval#3]
### Feature type

DataFetcher (Retrieves data)

### 🚀 The feature, motivation and pitch

Hi there,

Thanks for the package, I enjoy using it. I was wondering if it is possible to add more fields to the Dataset besides the "text" and "label" fields. I want this, because I want to filter the final produced data values based on my dataset field `is_synthetic`. 

Because I use the `BertEmbeddings` `nlpsets` function, I cannot/do not know how to, link the text embeddings back to the original datum. So, now I lost the "is_synthetic" information. It also seems that the Dataloader shuffles the data, so linking the data based on the index does not work.

### Alternatives

I tried to link the data based on index, but the data gets shuffled. I tried to find in the code where `Shuffle=True` and turned it to `false`, but the data still seems to be shuffled. (Also shuffling the data is a good thing to do, so turning it off is bad behaviour)

I tried to decode the BertEmbeddings to text and then manually just match the data points, but decoding embeddings back to text seems to be impossible.

### Additional context

I have generated synthetic data points, and I want to check if I generate high-value synthetic data. To do this, I want to perform the DVRL data valuation using BertEmbeddings and afterwards filter on `is_synthetic` to create two boxplots.

**Comment by heblol** [comment]
Hi there, I got it. I did not see it, but there is a object field "train_indices", "test_indices" and "validation_indices"

Wrote a small script to add the data values to the original dataset

```
import pandas as pd
import numpy as np


def retrieve_original_data_points(original_dataset: pd.DataFrame, indices: np.array):
    """
        Get the original data points from a certain set of indices
    """
    og = original_dataset.loc[indices]
    og["index_in_ds"] = og.index
    # og.reset_index(drop=True, inplace=True)

    return og


def combine_datavalues_indices(data_values: pd.DataFrame, indices: pd.DataFrame):
    """
        Combine the data values the indices
    """
    indices.rename(columns={0: "index_in_ds"}, inplace=True)
    indices["data_value"] = data_values

    return indices


def combine_datavalues_original_dataset(original_dataset: pd.DataFrame, data_values: pd.DataFrame, indices: pd.DataFrame):
    """
        Combine the data values together with the indices and the original dataset
    """

    # Filter the original dataset s.t. we only keep the indices
    og = retrieve_original_data_points(
        original_dataset, indices.to_numpy().flatten())

    # og has columns
    # index, text, label
    dv = combine_datavalues_indices(data_values, indices)

    return pd.merge(og, dv, on="index_in_ds", how="outer")
```

**Comment by ykwon0407** [comment]
@heblol Thank you so much for the code snippet. We are currently working on this matter and will get back to you soon!

**Comment by kevinfjiang** [comment]
@heblol 

Thanks so much for the feature request! it looks like the bbc-embeddings had a subset selected to limit the size of the data in memory. I've removed that shuffling and apologize for any of the confusion it may have caused and you can expect a new push soon (c0e560477975e44d2913bc722b7aee0f7e7b58e1).

We'd welcome a pull-request if you want to contribute to the library!

Below I have a snippet of how we can possibly integrate it with to extract the data and data values from the `DataFetcher`, lmk your thoughts.

```python

def separate_dataval(fetcher: DataFetcher, data_values: np.ndarray, in_group: Sequence[int]) -> dict[str, np.ndarray]: 
    """Separates data and data values based on a list of the original indices of the dataset."""
    train_indices = set(fetcher.train_indices)

    in_train = list(train_indices.intersection(in_group))
    out_train = list(train_indices.difference(in_group))
    val_to_index = {v: i for i, v in enumerate(fetcher.train_indices)}


    return {
        "in_data": fetcher.covar[in_train],
        "in_data_values": data_values[[val_to_index[i] for i in in_train]],
        "out_data": fetcher.covar[out_train],
        "out_data_values": data_values[[val_to_index[i] for i in out_train]]
    }
  


```

**Comment by kevinfjiang** [comment]
#NOTE you may still receive the following error message: 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible.
Successfully installed geomloss-0.2.6 keopscore-2.1.2 matplotlib-3.8.1 multimethod-1.10 mypy-extensions-1.0.0 opendataval-1.3.0 pandera-0.15.2 pybind11-2.11.1 pykeops-2.1.2 scikit-learn-1.3.2 torcheval-0.0.7 tqdm-4.64.1 typeguard-4.1.5 typing-extensions-4.8.0 typing-inspect-0.9.0

WARNING: The following packages were previously imported in this runtime:
  [matplotlib,mpl_toolkits]
You must restart the runtime in order to use newly installed versions.
```

I think you can just restart the runtime and use opendataval as needed. Should this change please open a new bug or comment in this thread!

## Evidence
[Google colab ](https://colab.research.google.com/drive/1tGPmAI5d43TVt0MEMWeueJ1-O5S6NsCq?usp=sharing)
