### ISSUE TITLE
Saving each batch requires a lot of storage, why was this changed?

### ISSUE THREAD

**Issue by heblol** [opendataval/opendataval#6]
### 🐛 Describe the bug

Hi there, thanks again for this package.

I updated my fork (Last forked it 2 months ago). I saw that the `nlpsets.py` was changed, however, I cannot load my .pt file from the folder anymore. Previously the `BertEmbeddings` returned the embeddings, but now it returns a `FolderDataset`. It does not seem to be loaded correctly in the fetcher. The fetcher line `self._add_data(*self.dataset.load_data(cache_dir, force_download))`, seems not to load the covarates anymore. I get the error

``ValueError: Covariates and Labels must be of same length. covar=0 labels=50486``

Besides this error, I saw that the BertEmbedding now saves each batch to file, my embedded dataset (imdb) went from 200mb (after embedding it) to 20GB. Not sure why we want to save each batch?

## How to solve
I solved it by reverting the change of the BertEmbedding, and now return embeddings again by using `torch.load(cache_file)`. I also removed the batch saving and just saved the final embeddings. 

I think this change can also be done inside the `FolderDataset.load` function by loading the final embedded.pt file. But i dont know the rationale behind the refactoring everything to the `FolderDataset`, and the final embedded.pt file was changed to batches. Not sure the rational behind it, so not sure if I can create PR doing this?

### My workaround
_Maybe this is not the best way now I am thinking about it because the `pooled_embeddings_list` is now fully saved in memory. However, the code below works for the IMDb dataset_

Code if there was a cache match (note, i added a new file called `embed_file_name = f"{func.__name__}_{len(labels)}_embed.pt"`

```

        dataset, labels = func(cache_dir, force_download, *args, **kwargs)

        embed_file_name = f"{func.__name__}_{len(labels)}_embed.pt"
        embed_path = f"{cache_dir}/{func.__name__}_embed"

        print("This is the cache_dir", cache_dir)

        if FolderDataset.exists(Path(f"{embed_path}")):
            print(f"# Found Cached dataset!", embed_path)
            nlp_embeddings = torch.load(f"{embed_path}/{embed_file_name}")
            print("Loaded embeddings", nlp_embeddings)
            return nlp_embeddings, labels
            # return FolderDataset.load(embed_path), labels # <-- Instead of returning the FoldeRDataset.load, i return the embeddings
```

```
 # Initialize an empty list to store pooled embeddings
        pooled_embeddings_list = []  # <-- Added a list of all embeddings

        print("-" * 40)
        print(
            "# Need to tokenize and embedd all datapoints. This can take a while with large datasets."
        )
        print("-" * 40)
        for batch_num, batch in enumerate(tqdm(batched(dataset, n=batch_size))):
            bert_inputs = tokenizer.__call__(
                batch,
                max_length=200,
                padding=True,
                truncation=True,
                return_tensors="pt",
            ).to(device)
            bert_inputs = {inp: bert_inputs[inp] for inp in tokenizer.model_input_names}

            with torch.no_grad():
                pool_embed = bert_model(**bert_inputs)[0]
                word_embeddings = pool_embed.detach().cpu()[:, 0]

                # I added this line of code:
                pooled_embeddings_list.append(word_embeddings) # <-- Instead of writing everything to disk, i save it in the list.

            # folder_dataset.write(batch_num, word_embeddings)

        # Concatenate the pooled embeddings from all batches
        pooled_embeddings = torch.cat(pooled_embeddings_list, dim=0)

        ### -- I created this, saving the model -- ###
        if not os.path.exists(cache_dir):
            print(
                f"""cache dir does not exist, creating it cache_dir={
                  cache_dir} """
            )
            os.mkdir(cache_dir)

        # Concatenate the pooled embeddings from all batches
        torch.save(pooled_embeddings.detach(), f"{embed_path}/{embed_file_name}")  # <-- Saving embedding file.
        ### -- /END I created this, saving the model -- ###

        folder_dataset.save()
        print("-" * 40)
        print("# Finished BertEmbeddings wrapper.")
        print("-" * 40)

        return pooled_embeddings, np.array(labels) # <-- Returning pooled_embeddings
```

### Version

1.3.0

### Operating System

MacOS

**Comment by kevinfjiang** [comment]
Hi there,

Apologies about the delay in getting to this. We recognized that the random shuffling that we previously had was a problem. 

## Reasoning 
To explain the rationale, we save each batch as a file, so that the PyTorch Dataloader can load batches into memory instead of the entire dataset at a given time. This allows us to remove the random shuffling that we once had. 

## Solution
[V1.3](https://github.com/opendataval/opendataval/releases/tag/v1.3.0) chose to go with the entire dataset embeddings. In the time being, I'd recommend using [V1.2.1](https://github.com/opendataval/opendataval/releases/tag/v1.2.1) In a future PR I'll add something to specify the maximum number of data points we will create embedding for (something the user passes in). 

I'll also look into the first bug you mentioned where the lengths aren't being loaded. 

Thanks,
Kevin
